### ISSUE TITLE
How to config https with nodeport

### ISSUE THREAD

**Issue by 66545shiwo** [mfanoffice/dataease-helm#13]
I find the way for ingress in `values.yaml`  
```
ingress:
  enabled: false
  host: demo.apps.dataease.com
  annotations: {}
    ## example for ingress annotions.
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"      
  https:
    enabled: false
    secretName: ""
```
I want to know how to config https with k8s nodeport.
Thank you !
